# WEEK 1 
## TAKE HOME PROBLEMS




Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [2]:
import numpy as np

In [79]:
A = np.random.random((2,3))
B = np.random.random((2,3))

In [80]:
A

array([[0.18534435, 0.92314116, 0.66256173],
       [0.34583653, 0.66264526, 0.50618763]])

In [81]:
B

array([[0.92827896, 0.35602991, 0.05468583],
       [0.26342813, 0.43891719, 0.53321642]])

In [83]:
V = np.vstack((A,B))

In [84]:
V

array([[0.18534435, 0.92314116, 0.66256173],
       [0.34583653, 0.66264526, 0.50618763],
       [0.92827896, 0.35602991, 0.05468583],
       [0.26342813, 0.43891719, 0.53321642]])

In [85]:
H = np.hstack((A,B))

In [86]:
H

array([[0.18534435, 0.92314116, 0.66256173, 0.92827896, 0.35602991,
        0.05468583],
       [0.34583653, 0.66264526, 0.50618763, 0.26342813, 0.43891719,
        0.53321642]])

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [87]:
A = np.array([[0,1,2],[2,3,4],[4,5,6]])
B = np.array([[5,6,7],[6,7,8],[7,8,9]])

In [88]:
np.intersect1d(A,B)

array([5, 6])

3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [99]:
A = np.random.randint(1, 10, (2, 3, 4))

In [100]:
A

array([[[5, 9, 7, 9],
        [6, 6, 9, 5],
        [3, 7, 5, 9]],

       [[2, 6, 1, 6],
        [9, 1, 7, 3],
        [9, 2, 3, 4]]])

In [101]:
A[np.where((A>5) & (A<10))]

array([9, 7, 9, 6, 6, 9, 7, 9, 6, 6, 9, 7, 9])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [119]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [136]:
iris[np.where((iris[:,2].astype('float') > 1.5) & (iris[:,0].astype('float') < 5.0))]

array([[b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4.5', b'1.7', b'Iris-virginica']], dtype=object)

Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
"""Your code goes here"""

output
```


In [141]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species


In [142]:
unique_species = np.unique(grouping_column)

output = []
for species in unique_species:
    mean_value = np.mean(numeric_column[grouping_column == species])
    output.append((species.decode('utf-8'), mean_value))  


In [143]:
output

[('Iris-setosa', 3.418),
 ('Iris-versicolor', 2.7700000000000005),
 ('Iris-virginica', 2.974)]

Pandas Questions

5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [144]:
import pandas as pd


6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


7. How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))