# WEEK 2
## TAKE HOME PROBLEMS




Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np

In [2]:
A = np.random.random((2,3))
B = np.random.random((2,3))

In [3]:
A

array([[0.83664138, 0.94093872, 0.83165798],
       [0.67868681, 0.41843887, 0.61254769]])

In [4]:
B

array([[0.64745858, 0.09368584, 0.97645959],
       [0.74864945, 0.12505504, 0.23715936]])

In [5]:
V = np.vstack((A,B))

In [6]:
V

array([[0.83664138, 0.94093872, 0.83165798],
       [0.67868681, 0.41843887, 0.61254769],
       [0.64745858, 0.09368584, 0.97645959],
       [0.74864945, 0.12505504, 0.23715936]])

In [7]:
H = np.hstack((A,B))

In [8]:
H

array([[0.83664138, 0.94093872, 0.83165798, 0.64745858, 0.09368584,
        0.97645959],
       [0.67868681, 0.41843887, 0.61254769, 0.74864945, 0.12505504,
        0.23715936]])

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [9]:
A = np.array([[0,1,2],[2,3,4],[4,5,6]])
B = np.array([[5,6,7],[6,7,8],[7,8,9]])

In [10]:
np.intersect1d(A,B)

array([5, 6])

3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [11]:
A = np.random.randint(1, 10, (2, 3, 4))

In [12]:
A

array([[[6, 9, 5, 7],
        [5, 8, 7, 2],
        [5, 4, 5, 2]],

       [[8, 9, 5, 6],
        [3, 9, 1, 6],
        [3, 6, 3, 6]]])

In [13]:
A[np.where((A>5) & (A<10))]

array([6, 9, 7, 8, 7, 8, 9, 6, 9, 6, 6, 6])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [15]:
iris[np.where((iris[:,2].astype('float') > 1.5) & (iris[:,0].astype('float') < 5.0))]

array([[b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4.5', b'1.7', b'Iris-virginica']], dtype=object)

Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
"""Your code goes here"""

output
```


In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species


In [17]:
unique_species = np.unique(grouping_column)

output = []
for species in unique_species:
    mean_value = np.mean(numeric_column[grouping_column == species])
    output.append((species.decode('utf-8'), mean_value))  


In [18]:
output

[('Iris-setosa', 3.418),
 ('Iris-versicolor', 2.7700000000000005),
 ('Iris-virginica', 2.974)]

Pandas Questions

5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [19]:
import pandas as pd


In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


In [21]:
df.info

<bound method DataFrame.info of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Pas

In [22]:
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]


In [23]:
filtered_df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


In [25]:
df.info

<bound method DataFrame.info of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Pas

In [26]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

/var/folders/rz/z8zwgz216dnbv6q92zly75200000gn/T/ipykernel_78128/4257016234.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/var/folders/rz/z8zwgz216dnbv6q92zly75200000gn/T/ipykernel_78128/4257016234.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting

In [27]:
df[['Min.Price', 'Max.Price']].isnull().sum()

Min.Price    0
Max.Price    0
dtype: int64

In [28]:
df.info

<bound method DataFrame.info of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Pas

7. How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [29]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [30]:
df.info

<bound method DataFrame.info of      0   1   2   3
0   34  39  11  20
1   33  25  27  30
2   10  28  22  19
3   18  13  39  29
4   34  37  35  17
5   17  36  28  20
6   25  32  13  18
7   19  31  35  11
8   11  11  39  18
9   37  23  15  29
10  13  12  14  20
11  34  25  10  19
12  30  16  12  31
13  19  29  14  20
14  28  12  16  35>

In [31]:
filtered_df = df[df.sum(axis=1) > 100]

In [32]:
filtered_df

0   1   2   3
0  34  39  11  20
1  33  25  27  30
4  34  37  35  17
5  17  36  28  20
9  37  23  15  29